import type { ChronicleDay } from './types'

export const TODAY = '2026-08-22'

export const initialDays: ChronicleDay[] = [
  {
    date: '2026-08-12',
    entries: [
      {
        id: 'd12-1',
        kind: 'photo',
        author: 'Dad',
        time: '07:42',
        source: 'chat',
        image: '/photos/garden.jpg',
        caption: 'The first tomatoes from the garden',
      },
      {
        id: 'd12-2',
        kind: 'note',
        author: 'Mom',
        time: '08:03',
        source: 'direct',
        body: 'Dad picked the first tomatoes this morning. He is very proud of them.',
      },
    ],
  },
  {
    date: '2026-08-14',
    entries: [
      {
        id: 'd14-1',
        kind: 'photo',
        author: 'Kate',
        time: '16:18',
        source: 'chat',
        image: '/photos/flowers.jpg',
        caption: 'Flowers from the walk home',
      },
      {
        id: 'd14-2',
        kind: 'voice',
        author: 'Kate',
        time: '16:22',
        source: 'direct',
        duration: '0:19',
        body: 'I found these on the way home and thought Grandma would love them.',
      },
    ],
  },
  {
    date: '2026-08-15',
    entries: [
      {
        id: 'd15-1',
        kind: 'photo',
        author: 'Kate',
        time: '11:20',
        source: 'chat',
        image: '/photos/dinner.jpg',
        caption: 'Saturday lunch at Grandma’s',
      },
      {
        id: 'd15-2',
        kind: 'photo',
        author: 'Grandma',
        time: '12:05',
        source: 'chat',
        image: '/photos/pie.jpg',
        caption: 'Apple pie before everyone arrived',
      },
      {
        id: 'd15-3',
        kind: 'voice',
        author: 'Grandma',
        time: '18:04',
        source: 'direct',
        duration: '0:51',
        body: 'Alex, there is another slice of pie waiting for you tomorrow.',
      },
    ],
  },
  {
    date: '2026-08-18',
    entries: [
      {
        id: 'd18-1',
        kind: 'note',
        author: 'Mom',
        time: '08:12',
        source: 'direct',
        body: 'Dad has an appointment on Thursday. Let me know who can drive him.',
      },
      {
        id: 'd18-2',
        kind: 'voice',
        author: 'Dad',
        time: '09:30',
        source: 'direct',
        duration: '0:24',
        body: 'No need to worry. I feel fine, and the appointment should be quick.',
      },
    ],
  },
  {
    date: '2026-08-20',
    entries: [
      {
        id: 'd20-1',
        kind: 'photo',
        author: 'Dad',
        time: '16:40',
        source: 'chat',
        image: '/photos/kitchen.jpg',
        caption: 'The kitchen halfway through dinner',
      },
      {
        id: 'd20-2',
        kind: 'photo',
        author: 'Mom',
        time: '19:05',
        source: 'chat',
        image: '/photos/coffee.jpg',
        caption: 'Coffee after dinner',
      },
      {
        id: 'd20-3',
        kind: 'voice',
        author: 'Alex',
        time: '21:18',
        source: 'direct',
        duration: '0:28',
        body: 'I made it home. Let us call tomorrow evening.',
      },
    ],
  },
  {
    date: '2026-08-21',
    entries: [
      {
        id: 'd21-1',
        kind: 'video',
        author: 'Mom',
        time: '15:30',
        source: 'direct',
        duration: '0:12',
        image: '/photos/kids.jpg',
        caption: 'A quick hello from the park',
      },
      {
        id: 'd21-2',
        kind: 'photo',
        author: 'Kate',
        time: '17:08',
        source: 'chat',
        image: '/photos/tea.jpg',
        caption: 'Tea on the balcony',
      },
      {
        id: 'd21-3',
        kind: 'note',
        author: 'Dad',
        time: '22:11',
        source: 'direct',
        body: 'Thank you for coming. Breakfast is in the fridge.',
      },
    ],
  },
  {
    date: '2026-08-22',
    entries: [
      {
        id: 'd22-1',
        kind: 'photo',
        author: 'Alex',
        time: '09:14',
        source: 'direct',
        image: '/photos/coffee.jpg',
        caption: 'Slow Saturday morning',
      },
      {
        id: 'd22-2',
        kind: 'photo',
        author: 'Grandma',
        time: '16:20',
        source: 'chat',
        image: '/photos/pie.jpg',
        caption: 'The pie is ready',
      },
      {
        id: 'd22-3',
        kind: 'video',
        author: 'Kate',
        time: '17:10',
        source: 'direct',
        duration: '0:08',
        image: '/photos/cook.jpg',
        caption: 'Grandma showing the recipe',
      },
      {
        id: 'd22-4',
        kind: 'photo',
        author: 'Dad',
        time: '18:40',
        source: 'chat',
        image: '/photos/flowers.jpg',
        caption: 'Flowers for the table',
      },
      {
        id: 'd22-5',
        kind: 'voice',
        author: 'Mom',
        time: '12:46',
        source: 'chat',
        duration: '0:36',
        body: 'Have you eaten? There is soup on the stove.',
      },
      {
        id: 'd22-6',
        kind: 'note',
        author: 'Kate',
        time: '13:02',
        source: 'direct',
        body: 'I will send a photo tonight. It is just a new hair color.',
      },
      {
        id: 'd22-7',
        kind: 'voice',
        author: 'Grandma',
        time: '14:18',
        source: 'direct',
        duration: '0:22',
        body: 'The pie is ready. Come by while it is still warm.',
      },
      {
        id: 'd22-8',
        kind: 'voice',
        author: 'Dad',
        time: '15:04',
        source: 'chat',
        duration: '0:18',
        body: 'I will be home after six. I can pick everyone up.',
      },
      {
        id: 'd22-9',
        kind: 'note',
        author: 'Alex',
        time: '16:08',
        source: 'direct',
        body: 'I bought tea. See you at Grandma’s tonight.',
      },
    ],
  },
]
